### PR TITLE
add realio

### PR DESCRIPTION
**Pull request by hoangdv2429**
This will add Realio to Keplr Dashbroad UI

### CODE REVIEW

**Comment by hoangdv2429** [comment]
@delivan Can you review this ? if we need to change anything, please let me know. Thank you!

**Comment by delivan** [comment]
@MasterPi-2124 sorry for the late addition. there was a bug in github action. It's added now.

**Comment by MasterPi-2124** [comment]
Hi, I just found out that there is also a repo that was mentioned in instructions of Kepler wallet: https://github.com/chainapsis/keplr-chain-registry. I also added Realio to this repo, but which repo is responsible for adding a new chain to Kepler? @delivan

**Comment by delivan** [comment]
@MasterPi-2124 that repo(keplr-chain-registry) is responsible for letting user adding a chain. if PR merged, your chain is showing on https://chains.keplr.app/ 
you also be able to let users add your chain on your frontend.

**Comment by hoangdv2429** [comment]
@delivan Thank you for the quick response. We just have a small problem left, which is the RIO token is still not listed on Keplr Dashboard eventhough the app is registered

**Comment by hoangdv2429** [comment]
also the price is not showing eventhough coingekko ID is on there https://www.coingecko.com/en/coins/realio-network

**Comment by hoangdv2429** [comment]
oh no, the previous submission missed that field. Let me fire another PR to fix it @delivan I'm so sorrry.

**Comment by delivan** [comment]
No problem! To clarify, adding a chain is different from registering an app here. Also, even if a chain is added to the Keplr wallet, chains that are not natively integrated into Keplr will not be displayed on the Keplr Dashboard. please check [this article](https://medium.com/chainapsis/keplr-explained-native-vs-suggest-chain-or-permissionless-integration-8e425f921086) for native/non-native integration.

**Comment by hoangdv2429** [comment]
@delivan Hi. Sorry to bother you at this hour. I have a little problem with https://chains.keplr.app/ , the currency that show up on it is wrong. it shouldn't be RST, instead it should be RIO as we have wrote it on https://github.com/chainapsis/keplr-chain-registry/blob/f796dedcb65e518e90ff582b4eac13c10ded740d/cosmos/realionetwork_3301.json#L12. Do you know what's wrong and how can we fix it ?

**Pull request merged**
